Burak-platform-logo
freedomcombination/monorepo pull request #1234
Opened 2024-04-22 21:10 UTC by myniqx

i have tested with caps. but i dont know how to run og.tsx

2024-04-23 10:03 UTC, 7alip requested changes
Thanks

2024-04-23 10:03 UTC, 7alip commented on packages/ui/src/components/Caps/Caps.tsx
> +      platform = 'trend-rights',
I know it was mentioned in the task: `Add platform: PlatformSlug to OgImageParams (default is trend-rights)` but I noticed that if `platform` will be part of `imageParams`, it will be difficult to update it when we change hashtag's platform.

It's probably best to get platform info directly from `post.hashtag.platform.slug`. Even if we don't save platform in `post.imageParams`, we can still extend imageParams with platform in `getHashtagBySlug`.

2024-04-23 10:03 UTC, 7alip commented on packages/ui/src/components/Caps/logos.tsx
> +  'trend-rights': (
I see it's previous filled logo

2024-04-24 08:19 UTC, myniqx commented on packages/ui/src/components/Caps/logos.tsx
> +  'trend-rights': (
i took lines from file. i didnt know they are different.

2024-04-24 13:59 UTC, 7alip commented on packages/services/src/api/og.tsx
> +    'trend-rights') as PlatformSlug
@myniqx How we hide logo in og.tsx?

2024-04-24 14:03 UTC, myniqx commented on packages/services/src/api/og.tsx
> +    'trend-rights') as PlatformSlug
I thought its enough to hide it in <Caps/> on the site. fixing it right away.

2024-04-24 15:54 UTC, 7alip approved these changes
Thanks

2024-04-24 15:56 UTC, merged