Burak-uploader
freedomcombination/monorepo pull request #1284
Opened 2024-05-12 15:51 UTC by myniqx

2024-05-12 17:38 UTC, MustafaTRKYLMZ commented
It is looking so perfect. But I am wondering that it is possible to upload other format at the same time such as pdf, exel and doc.

2024-05-14 00:24 UTC, 7alip approved these changes
Thanks

2024-05-14 00:27 UTC, 7alip requested changes
Thanks

2024-05-14 00:27 UTC, 7alip commented on packages/ui/src/components/FormUploader/MenuImageItem.tsx
> +  }, [url])
This comment can be removed after fixing

2024-05-14 00:27 UTC, 7alip commented on packages/ui/src/components/FormUploader/MenuImageItem.tsx
> +      {/* TODO: Display pdf icon for pdfs, File icon for other file types */}
This comment can be removed after fixing.

Icon wrapper box can have the same height as image.

2024-05-14 10:38 UTC, myniqx commented
file icons:
![image](https://github.com/freedomcombination/monorepo/assets/4520739/f1a9c1ff-f3d5-45ce-b04d-6c90b6e3e361)

it pastes as link when its not an image:
![image](https://github.com/freedomcombination/monorepo/assets/4520739/19b71a65-2507-4798-8951-de579e9d4654)

2024-05-14 11:28 UTC, 7alip commented
@myniqx The only thing left is to remove dimensions part if with or height is not available. It shows only `x` now

2024-05-14 12:46 UTC, myniqx commented
> @myniqx The only thing left is to remove dimensions part if with or height is not available. It shows only `x` now

```
           <VStack fontSize={'xs'} spacing={0}>
              <Box>original</Box>
              {isImage ? (
                <Box>
                  {file.width} x {file.height}
                </Box>
              ) : (
                <Box>{(file.size / 1024).toFixed(2)} kb</Box>
              )}
            </VStack>
```
its already removed. if file is image it ll show dimensions otherwise it ll show file size.
and beside image file they dont have fileformats so there ll be only this 'original' box with filesize, u can see in this image : 
![image](https://github.com/freedomcombination/monorepo/assets/4520739/79108a78-c870-4091-afc8-dabb069eebf2)

2024-05-16 13:58 UTC, 7alip approved these changes
Thanks

2024-05-16 13:59 UTC, merged