profile editing test done
freedomcombination/monorepo pull request #1579
Opened 2024-08-13 14:36 UTC by hilalnigarbasan

2024-08-14 19:23 UTC, 7alip requested changes
Thanks

2024-08-14 19:23 UTC, 7alip commented on packages/playwright/src/tests/profile-editing.spec.ts
> +    await page.evaluate(() => window.scrollTo(0, 0));
How would you know if the password was truly changed? You test if the user can log in with the updated password. You should usually use `expect` at the end of your test blocks.

```ts
// login
// update password
// login with updated password
// expect() => successful login, for example check if the profile button has username
```

2024-08-14 19:23 UTC, 7alip commented on packages/playwright/src/tests/profile-editing.spec.ts
> +    await page.getByTestId('button-submit-login').click();
These steps are used in all tests. I would create a `Dashboard.ts` page object model. 
There you could have `login(username: string, password: string) {}`  function and call this function in your tests. See login.spec.ts and Login.ts files

2024-08-14 19:23 UTC, 7alip commented on packages/playwright/src/tests/profile-editing.spec.ts
> +    // expect(isVisible).toBeTruthy();
Why these lines are commented out? Are tests failing with this assertion?

2024-08-14 19:23 UTC, 7alip commented on packages/playwright/src/tests/profile-editing.spec.ts
> +    await page.getByRole('button', { name: 'Change Password' }).click();
There is no assertion (`expect`) in this test block.

2024-08-14 19:23 UTC, 7alip commented on packages/playwright/src/tests/profile-editing.spec.ts
> +    await page.getByRole('button', { name: 'Save' }).click();
There is no assertion (`expect`) in this test block.

2024-08-14 19:23 UTC, 7alip commented on packages/playwright/src/tests/profile-editing.spec.ts
> +    await page.getByRole('button', { name: 'Save' }).click();
There is no assertion (`expect`) in this test block.

2024-08-14 19:23 UTC, 7alip commented on packages/playwright/src/tests/profile-editing.spec.ts
> +    await page.getByTestId('button-submit-login').click();
There is no assertion (`expect`) in this test block.

2024-08-14 19:23 UTC, 7alip commented on packages/playwright/src/tests/profile-editing.spec.ts
> +    const page1Promise = page.waitForEvent('popup');
What exactly is this promise and popup event for?

If it's necessary, I would give a more descriptive name to this variable, like: `popupEventPromise`, `waitingPopupPromise` etc.

2024-08-16 18:07 UTC, hilalnigarbasan commented
//How would you know if the password was truly changed? You test if the user can log in with the updated password. You should usually use expect at the end of your test blocks.

The case that the user can log in with the updated password was requested in the second acceptance criteria under ‘after editing able to access new credentials’.
That's why I tested it under the ‘User can display new credentials/ security’ test header.

<https://1drv.ms/i/s!AqbmDqNXtL_NhCGfDl7uogqv8KBo>
[https://blz04pap003files.storage.live.com/y4m2fIqH91YDJb-cUC9jXQyQs2FOR8wqKPItDjZo28IqvAQkfONZX7TCctl-PbqaLuZl1XDYt6xHun_-5xRctncyr8qZbriX9gNZacJugcW_v-dcxKz2TMT50KMeHy0_nmyb7PN__tXSYKIrJHTkVWcP9bxGwx3vVBCoZGO8nooZIIcLvJu8zND1dpyZTOWgc4U?width=200&height=150&cropmode=center]
[https://res.cdn.office.net/assets/mail/file-icon/png/cloud_blue_16x16.png]Screenshot 2024-08-16 at 20.00.28.png



//Why these lines are commented out? Are tests failing with this assertion?
Yes, the test was failing with this assertion but I found a new assertion instead.


________________________________
Gönderen: Talip Altas ***@***.***>
Gönderildi: 14 Ağustos 2024 Çarşamba 22:23
Kime: freedomcombination/monorepo ***@***.***>
Bilgi: Hilal Nigar BAŞAN ***@***.***>; Author ***@***.***>
Konu: Re: [freedomcombination/monorepo] profile editing test done (PR #1579)


@7alip requested changes on this pull request.

Thanks

________________________________

In packages/playwright/src/tests/profile-editing.spec.ts<https://github.com/freedomcombination/monorepo/pull/1579#discussion_r1717435571>:

> +    await page.getByTestId('input-email').fill('Admin8');
+    await page.getByTestId('input-password').click();
+    await page.getByTestId('input-password').fill('1234512345Ad');
+    await page.getByTestId('button-submit-login').click();
+    await page.evaluate(() => window.scrollTo(0, 0));
+    await page.getByRole('button', { name: 'Admin8' }).click();
+    await page.getByRole('menuitem', { name: 'Profile' }).click();
+    await page.getByRole('tab', { name: 'Security' }).click();
+    await page.getByPlaceholder('currentPassword').click();
+    await page.getByPlaceholder('currentPassword').fill('1234512345Ad');
+    await page.getByPlaceholder('Password', { exact: true }).click();
+    await page.getByPlaceholder('Password', { exact: true }).fill('1234567Ak');
+    await page.getByPlaceholder('passwordConfirmation').click();
+    await page.getByPlaceholder('passwordConfirmation').fill('1234567Ak');
+    await page.getByRole('button', { name: 'Change Password' }).click();
+    await page.evaluate(() => window.scrollTo(0, 0));


How would you know if the password was truly changed? You test if the user can log in with the updated password. You should usually use expect at the end of your test blocks.

// login
// update password
// login with updated password
// expect() => successful login, for example check if the profile button has username

________________________________

In packages/playwright/src/tests/profile-editing.spec.ts<https://github.com/freedomcombination/monorepo/pull/1579#discussion_r1717439147>:

> +    await page.goto(getVercelUrl('kunsthalte'))
+    await page.getByRole('button', { name: 'EN' }).click();
+    await page.getByRole('link', { name: 'Sign in' }).click();
+    await page.getByTestId('input-email').click();
+    await page.getByTestId('input-email').fill('Admin8');
+    await page.getByTestId('input-password').click();
+    await page.getByTestId('input-password').fill('1234512345Ad');
+    await page.getByTestId('button-submit-login').click();


These steps are used in all tests. I would create a Dashboard.ts page object model.
There you could have login(username: string, password: string) {} function and call this function in your tests. See login.spec.ts and Login.ts files

________________________________

In packages/playwright/src/tests/profile-editing.spec.ts<https://github.com/freedomcombination/monorepo/pull/1579#discussion_r1717440262>:

> +    // const errorMessageSelector = 'text=The provided current password is invalid';
+    // const isVisible = await page.isVisible(errorMessageSelector);
+    // expect(isVisible).toBeTruthy();


Why these lines are commented out? Are tests failing with this assertion?

________________________________

In packages/playwright/src/tests/profile-editing.spec.ts<https://github.com/freedomcombination/monorepo/pull/1579#discussion_r1717440892>:

> +    await page.getByRole('button', { name: 'EN' }).click();
+    await page.getByRole('link', { name: 'Sign in' }).click();
+    await page.getByTestId('input-email').click();
+    await page.getByTestId('input-email').fill('Admin8');
+    await page.getByTestId('input-password').fill('1234567Ak');
+    await page.getByTestId('button-submit-login').click();
+    await page.getByRole('button', { name: 'Admin8' }).click();
+    await page.getByRole('menuitem', { name: 'Profile' }).click();
+    await page.getByRole('tab', { name: 'Security' }).click();
+    await page.getByPlaceholder('currentPassword').click();
+    await page.getByPlaceholder('currentPassword').fill('1234567Ak');
+    await page.getByPlaceholder('Password', { exact: true }).click();
+    await page.getByPlaceholder('Password', { exact: true }).fill('1234512345Ad');
+    await page.getByPlaceholder('passwordConfirmation').click();
+    await page.getByPlaceholder('passwordConfirmation').fill('1234512345Ad');
+    await page.getByRole('button', { name: 'Change Password' }).click();


There is no assertion (expect) in this test block.

________________________________

In packages/playwright/src/tests/profile-editing.spec.ts<https://github.com/freedomcombination/monorepo/pull/1579#discussion_r1717441471>:

> +    await page.getByRole('button', { name: 'EN' }).click();
+    await page.getByRole('link', { name: 'Sign in' }).click();
+    await page.waitForTimeout(1000)
+    await page.getByTestId('input-email').click();
+    await page.getByTestId('input-email').fill('Admin8');
+    await page.getByTestId('input-password').click();
+    await page.getByTestId('input-password').fill('1234512345Ad');
+    await page.getByTestId('button-submit-login').click();
+    await page.evaluate(() => window.scrollTo(0, 0));
+    await page.getByRole('button', { name: 'Admin8' }).click();
+    await page.getByRole('menuitem', { name: 'Profile' }).click();
+    await page.getByRole('tab', { name: 'Socials' }).click();
+    await page.getByPlaceholder('linkedin').click();
+    await page.getByPlaceholder('linkedin').fill('https://www.linkedin.com/in/williamhgates/');
+    await page.evaluate(() => { window.scrollTo(0, document.body.scrollHeight); });
+    await page.getByRole('button', { name: 'Save' }).click();


There is no assertion (expect) in this test block.

________________________________

In packages/playwright/src/tests/profile-editing.spec.ts<https://github.com/freedomcombination/monorepo/pull/1579#discussion_r1717442149>:

> +    await page.goto(getVercelUrl('kunsthalte'))
+    await page.getByRole('button', { name: 'EN' }).click();
+    await page.getByRole('link', { name: 'Sign in' }).click();
+    await page.getByTestId('input-email').click();
+    await page.getByTestId('input-email').fill('Admin8');
+    await page.getByTestId('input-password').click();
+    await page.getByTestId('input-password').fill('1234512345Ad');
+    await page.getByTestId('button-submit-login').click();
+    await page.evaluate(() => window.scrollTo(0, 0));
+    await page.getByRole('button', { name: 'Admin8' }).click();
+    await page.getByRole('menuitem', { name: 'Profile' }).click();
+    await page.getByRole('tab', { name: 'Socials' }).click();
+    await page.getByPlaceholder('linkedin').click();
+    await page.getByPlaceholder('linkedin').fill('https://www.linkedin.com/in/williamhgates');
+    await page.evaluate(() => { window.scrollTo(0, document.body.scrollHeight); });
+    await page.getByRole('button', { name: 'Save' }).click();


Ther [...]

2024-08-17 14:23 UTC, 7alip commented on packages/playwright/src/tests/profile-editing.spec.ts
> +    // expect(isVisible).toBeTruthy();
> Yes, the test was failing with this assertion but I found a new assertion instead.

2024-08-17 14:23 UTC, 7alip commented on packages/playwright/src/tests/profile-editing.spec.ts
> +    await page.evaluate(() => window.scrollTo(0, 0));
> The case that the user can log in with the updated password was requested in the second acceptance criteria under ‘after editing able to access new credentials’.
That's why I tested it under the ‘User can display new credentials/ security’ test header.

2024-09-07 11:33 UTC, 7alip commented
@hilalnigarbasan I'll merge this into dev. I'm preparing dev environment for upcoming test cases.

2024-09-07 11:34 UTC, merged