Test dasbord verify
freedomcombination/monorepo pull request #1594
Opened 2024-08-19 20:29 UTC by safaktopkaya

2024-08-20 10:21 UTC, 7alip requested changes
Thanks

2024-08-20 10:21 UTC, 7alip commented on packages/playwright/src/tests/dasbord-verifiy.spec.ts
> +  await page.locator('.css-1x01hl1').first().click()
You should avoid using random generated classes because it may be different in each deploy.

Your test can pass locally but it seems it fails in the pipeline: https://github.com/freedomcombination/monorepo/actions/runs/10460458698/job/28966665614?pr=1594

2024-08-20 22:07 UTC, 7alip commented on packages/playwright/src/tests/dasbord-verifiy.spec.ts
> +  await page.getByRole('link', { name: 'Kunsten' }).first().click()
@safaktopkaya Do you only check whether the menus are clickable and visible in the correct language? Or do you also want to see if the links work and take you to the correct page? If you want to test whether the link functionalities work, you should add assertions after each click.

For example:

```ts
await page.getByRole('link', { name: 'Kunsten' }).first().click()
await page.waitForURL(<expected url>, { timeout: TEST_TIMEOUT })
await expect(page).toHaveURL(<expected url>)
```

Alternatively, you can test if the page title displayed in the correct language

```ts
await page.getByRole('link', { name: 'Kunsten' }).first().click()
await page.waitForLoadState('networkidle')
const title = await page.title()
await expect(title).toBe(<expected title>)
```

2024-08-23 20:23 UTC, safaktopkaya commented on packages/playwright/src/tests/dasbord-verifiy.spec.ts
> +  await page.getByRole('link', { name: 'Kunsten' }).first().click()
My test case these are;o I tested them by following these steps

-username/language bar should be visible
-page title should be visible as Home-Kunsthalte
-buttom menu bar/ buttons should be active / view activities ,arts , collections clicable and 
 direct to other page

2024-09-09 20:33 UTC, 7alip requested changes
Could you rename your file name to `07-verify-pages.spec.ts`

2024-09-09 20:33 UTC, 7alip commented on packages/playwright/src/tests/dasbord-verifiy.spec.ts
> +})
Let's remove this test. We will add dashboard tests later in a separate task.

2024-09-09 20:33 UTC, 7alip commented on packages/playwright/src/tests/dasbord-verifiy.spec.ts
> +test('Language bar', async ({ page }) => {
Could you update your tests with the following format:

```ts
import { expect, test } from '@playwright/test'

test.describe('07. Verify Pages', () => {
  test('TC-01: should display homepage in the correct language', async ({
    page,
  }) => {
    // Test steps
  })

  test('TC-02: should display arts categories in the correct language', async ({
    page,
  }) => {
    // Test steps
  })
})
```

2024-09-16 16:17 UTC, safaktopkaya commented on packages/playwright/src/tests/dasbord-verifiy.spec.ts
> +test('Language bar', async ({ page }) => {
Ican make update

2024-09-17 15:54 UTC, closed without merging