Reset Pagination After Applying Filters
freedomcombination/monorepo pull request #1669
Opened 2024-09-12 13:46 UTC by bbluechip

2024-09-12 13:50 UTC, bbluechip commented
in my last commit, code works on some cases... Page numbers reset if selected category contains more than one page and if you are on that page before you choose that category.

2024-09-12 20:09 UTC, 7alip requested changes
Thanks

2024-09-12 20:09 UTC, 7alip commented on packages/ui/src/components/CategoryFilter/CategoryFilter.tsx
> +  const resetPagination = () => {
It's not only about changing categories. `selectCategories` prop calls changeParam function.
This should be handled within the useChangeParams hook to ensure consistency across all query params updates.

I mentioned here: https://github.com/freedomcombination/monorepo/pull/1670#discussion_r1757455570

2024-09-15 05:58 UTC, 7alip requested changes
It's not based on the latest dev. There will be conflicts when you try to merge `dev` into your branch.

I would create a new branch from dev.

2024-09-15 05:58 UTC, 7alip commented on packages/ui/src/hooks/useChangeParam.tsx
> +
Not only `categories` filter but every possible filter other than `page` should be considered. For example, should the `page` filter should also be removed when people search `(?q=search)`. There can be other filters too.

2024-09-17 17:28 UTC, closed without merging