Teams
freedomcombination/monorepo pull request #1803
Opened 2024-10-15 12:47 UTC by MustafaTRKYLMZ

teams table added to strapi

2024-11-03 15:23 UTC, 7alip requested changes
I merged dev to fix conflicts on generated files

2024-11-03 15:23 UTC, 7alip commented on packages/types/team.ts
> +  platforms: Platform
```suggestion
  platform: Platform
```

2024-11-03 15:23 UTC, 7alip commented on packages/types/team.ts
> +  platforms: Platform
You could add PlatformRelationInput and other mutation related types.

2024-11-03 15:23 UTC, 7alip commented on packages/types/strapi.ts
> +  | Team
TeamCreateInput and TeamUpdate input types could be added.

2024-11-06 19:14 UTC, MustafaTRKYLMZ commented
What should we do know? Can you look for feedback  ? @7alip

2024-11-06 21:56 UTC, 7alip commented on packages/ui/components/AddMemberDialog/AddMemberDialog.tsx
> +            /> */}
This should be fixed @MustafaTRKYLMZ

2024-11-15 13:39 UTC, merged