Mlalek/onboard 02
freedomcombination/monorepo pull request #1929
Opened 2024-11-11 20:24 UTC by MLalek

Onboarding 02 Test-write

2024-11-11 20:24 UTC, MLalek commented
Pls. review the task

2024-11-11 22:22 UTC, 7alip requested changes
Thanks. Could you update your test in the same branch?

2024-11-11 22:22 UTC, 7alip commented on playwright/onboarding/02-write-test.spec.ts
> +    .isVisible()
What is `page.pause` for here?

There is no assertion here, without `expect` this test will always pass. Visibility test could be something like this:

```ts
const title = page.locator('<page-selector-here>')

// I don't recommend isVisible
const isTitleVisible = await title.isVisible()
await expect(isTitleVisible).toBe(true)

// I recommend toBeVisible over isVisible
await expect(title).toBeVisible()
```

But, even if you would check the visibility of the title, it would not cover the criteria.

---

I don't see any assertion for checking if the title contains `Playwright`.

- [ ] Assign the locator to a variable `const title = ...`
- [ ] Check if the locator contains (`Playwright`)

2024-11-11 22:22 UTC, 7alip commented on playwright/onboarding/02-write-test.spec.ts
> +        .isVisible()
Again, this code does nothing here. This whole block means only `true` value. And it's not being used for anything.
Wouldn't you check if the title has the correct text (Whatever you see on the website)

```ts
const title = page.locator("")
expect (title).toBe("<Exact title content>")
  
// Alternatively
const titleContent = await title.textContent()
expect(titleContent).toBe("<Exact title content>")
```

2024-11-11 22:22 UTC, 7alip commented on playwright/onboarding/02-write-test.spec.ts
> +      await page.locator('#nav-bar :text("Pricing")').isVisible
Same comment here

2024-11-12 13:17 UTC, MLalek commented on playwright/onboarding/02-write-test.spec.ts
> +    .isVisible()
I made the necessary changes.

2024-11-12 13:17 UTC, MLalek commented on playwright/onboarding/02-write-test.spec.ts
> +        .isVisible()
I made the necessary changes.

2024-11-12 13:18 UTC, merged